version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run client:install
          name: Install client
      - run:
          command: npm run client:build
          name: Build client

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master