version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - only-on-branch: master
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_and_test:
    jobs:
      - build_and_test
